Try to resolve vercel deployment type errors
[18:10:02.944] Running build in Washington, D.C., USA (East) – iad1
[18:10:03.060] Cloning github.com/BCFCODE/BCFCODEwars (Branch: connectCodewars, Commit: 7103231)
[18:10:04.127] Cloning completed: 1.067s
[18:10:09.418] Restored build cache from previous deployment (6mhAMKNjjCtcDwyCScWYzPcMzkeQ)
[18:10:09.480] Running "vercel build"
[18:10:09.936] Vercel CLI 37.8.0
[18:10:10.884] Detected `pnpm-lock.yaml` version 9 generated by pnpm@9.x
[18:10:10.897] Installing dependencies...
[18:10:11.645] Lockfile is up to date, resolution step is skipped
[18:10:11.768] Already up to date
[18:10:12.528]
[18:10:12.559] Done in 1.6s
[18:10:12.590] Running "pnpm run build"
[18:10:13.118]
[18:10:13.119] > bcfcodewars@0.1.0 build /vercel/path0
[18:10:13.119] > next build
[18:10:13.119]
[18:10:15.326] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[18:10:15.327] This information is used to shape Next.js' roadmap and prioritize features.
[18:10:15.327] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[18:10:15.327] https://nextjs.org/telemetry
[18:10:15.327]
[18:10:15.524]   ▲ Next.js 14.2.15
[18:10:15.524]
[18:10:15.696]    Creating an optimized production build ...
[18:10:58.770]  ✓ Compiled successfully
[18:10:58.771]    Linting and checking validity of types ...
[18:11:05.718] Failed to compile.
[18:11:05.719]
[18:11:05.719] ./auth.ts:62:28
[18:11:05.719] Type error: Cannot find name 'session'.
[18:11:05.720]
[18:11:05.724] [0m [90m 60 |[39m       request[33m:[39m [33mNextRequest[39m[33m;[39m[0m
[18:11:05.724] [0m [90m 61 |[39m     }) {[0m
[18:11:05.724] [0m[31m[1m>[22m[39m[90m 62 |[39m       [36mconst[39m isLoggedIn [33m=[39m [33m![39m[33m![39msession[33m?[39m[33m.[39muser[33m;[39m[0m
[18:11:05.724] [0m [90m    |[39m                            [31m[1m^[22m[39m[0m
[18:11:05.724] [0m [90m 63 |[39m       [36mconst[39m isPublicPage [33m=[39m nextUrl[33m.[39mpathname[33m.[39mstartsWith([32m"/public"[39m)[33m;[39m[0m
[18:11:05.724] [0m [90m 64 |[39m[0m
[18:11:05.724] [0m [90m 65 |[39m       [36mif[39m (isPublicPage [33m||[39m isLoggedIn) {[0m
[18:11:05.765]  ELIFECYCLE  Command failed with exit code 1.
[18:11:05.787] Error: Command "pnpm run build" exited with 1
[18:11:06.148]